### ISSUE TITLE
waternode subdomain

### ISSUE THREAD

**Issue by dylanlee** [CIROH-UA/ciroh-ua.github.io#2]
**1.	Requester Information:**
Dylan Lee
dylan.lee@noaa.gov

**2.	Project Information:** 
The water node website will be a collaborative effort between CIROH, NOAA CoastWatch, and the National Water Center. The purpose of the website will be to intake remote sensing data relevant to hydrological modeling, prediciton, and analysis. The data will come from a variety of sources from within NOAA, CIROH, as well as potentially other agencies. This data will be disseminated to CIROH researchers, Water Center operations, and the general public.  

The other main purpose of the website is to serve as an educational platform and facilitator for the use of satellite imagery so that stakeholders that aren't experts in the processing and acquisition of remote sensing data can still use remote sensing data in their research efforts. 

**3.	name of subdomain:** 
waternode.ciroh.org

**4.	url of serving address:**
ec2-54-89-201-212.compute-1.amazonaws.com

**Comment by benlee0423** [comment]
@dylanlee 
It is done. Only thing is serving url will get changed when the instance stop/start.
You might want to use [elastic IP](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html) with the instance, which does not change even after stop/start the instance.

**Comment by dylanlee** [comment]
Great yes let's see if we can get an elastic IP setup

**Comment by benlee0423** [comment]
@dylanlee 
I have allocated elastic IP to the instance.
NEW IP: 54.86.113.134
You need to setup your server running on the instance correctly.
I am getting
`502 Bad Gateway` error when I access to it.

**Comment by benlee0423** [comment]
Done
