### ISSUE TITLE
Request to setup DKIM authentication for hydroserver.ciroh.org

### ISSUE THREAD

**Issue by daniel-slaugh** [CIROH-UA/ciroh-ua.github.io#3]
I'm setting up Amazon SES for password resets in HydroServer and need to paste the CNAME records in our domain's DNS server to get the DKIM authentication working. I have the three CNAMEs Amazon generated, can I pass them along to someone to paste in the server for me?

Email: 
daniel.slaugh@usu.edu

**Comment by benlee0423** [comment]
Done
