### ISSUE TITLE
CNAME record to allow https

### ISSUE THREAD

**Issue by romer8** [CIROH-UA/ciroh-ua.github.io#5]
**1.	Requester Information:**
Giovanni Romero
gromero@aquaveo.com

**2.	Project Information:** 
CNAME to allow http certificate

**3.	name of subdomain:** 
portal.ciroh.org

**4.	needed info**
CNAME name  _91b2da70f100ba4ad98ed5ccda995921.portal.ciroh.org.
CNAME value _62077b39b931e7e75783e307d699dde7.qqqkmlyjyg.acm-validations.aws.

**Comment by benlee0423** [comment]
This is done already.
@romer8 
Reopen it again if you need any further request.
